import { StyleSheet } from 'react-native';
import { moderateScale, verticalScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  headerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F2',
  },
  iconContainer: {
    width: moderateScale(35),
    height: moderateScale(35),
    borderRadius: moderateScale(20),
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: moderateScale(8),
    borderWidth: 1,
    borderColor: '#F2F2F2',
  },
  locationTextWrapper: {
    flex: 1,
  },
  offersNearText: {
    fontFamily: 'Manrope-Bold',
    fontSize: moderateScale(12),
    color: '#828282',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationText: {
    fontFamily: 'Manrope-Bold',
    fontSize: moderateScale(14),
    color: '#1A1A1A',
    marginRight: moderateScale(4),
  },
  searchContainer: {
    marginTop: verticalScale(10),
    marginHorizontal: moderateScale(16),
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    height: verticalScale(40),
    borderRadius: moderateScale(100),
    borderWidth: 1,
    borderColor: '#E8EAED',
    backgroundColor: '#FFFFFF',
  },
  searchInput: {
    fontSize: moderateScale(13),
    color: '#1A1A1A',
    height: verticalScale(35),
    backgroundColor: 'transparent',
    paddingHorizontal: moderateScale(8),
    fontFamily: 'Manrope-Bold',
    flex: 1,
  },
  autocompleteListView: {
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(12),
    marginTop: verticalScale(5),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#F2F2F2',
    position: 'absolute',
    top: verticalScale(40),
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  autocompleteRow: {
    padding: moderateScale(12),
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
  },
  autocompleteSeparator: {
    height: 1,
    backgroundColor: '#F2F2F2',
  },
  autocompleteDescription: {
    fontSize: moderateScale(13),
    color: '#1A1A1A',
    fontFamily: 'Manrope-Medium',
  },
  autocompletePoweredContainer: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    borderBottomRightRadius: moderateScale(12),
    borderBottomLeftRadius: moderateScale(12),
    borderColor: '#F2F2F2',
    borderTopWidth: 1,
    height: verticalScale(35),
    paddingRight: moderateScale(12),
  },
  filterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(12),
    paddingHorizontal: moderateScale(16),
    zIndex: 1,
  },
  filterButton: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    borderWidth: 1,
    borderColor: '#E8EAED',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: moderateScale(8),
  },
  categoryScroll: {
    flex: 1,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    height: moderateScale(35),
    borderRadius: moderateScale(20),
    borderWidth: 1,
    borderColor: '#E8EAED',
    backgroundColor: '#FFFFFF',
    marginRight: moderateScale(8),
  },
  activeCategoryButton: {
    borderColor: '#1A1A1A',
    backgroundColor: '#F8F9FA',
  },
  categoryText: {
    fontSize: moderateScale(13),
    fontFamily: 'Manrope-Bold',
    color: '#5F6368',
    marginLeft: moderateScale(6),
  },
  activeCategoryText: {
    color: '#1A1A1A',
  },
  mapContainer: {
    flex: 1,
    marginTop: verticalScale(12),
    backgroundColor: '#F5F5F5',
  },
  map: {
    flex: 1,
  },

  userLocationWrapper: {
    padding: moderateScale(5),
    borderRadius: moderateScale(100),
    backgroundColor: 'rgba(114, 16, 255, 0.2)',
  },
  userLocationDot: {
    width: moderateScale(20),
    height: moderateScale(20),
    borderRadius: moderateScale(10),
    backgroundColor: '#7210FF',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  listButton: {
    position: 'absolute',
    bottom: verticalScale(20),
    alignSelf: 'center',
    backgroundColor: '#7210FF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(20),
    paddingVertical: moderateScale(10),
    borderRadius: moderateScale(25),
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    zIndex: 10,
  },
  listButtonText: {
    color: '#FFFFFF',
    fontSize: moderateScale(14),
    fontFamily: 'Manrope-Bold',
    marginLeft: moderateScale(8),
  },
});
